services:
  nextcloud-db:
    image: mariadb:10.6
    container_name: ${MYSQL_HOST}
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  nextcloud:
    image: nextcloud:28
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - "8091:80"
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      OVERWRITEPROTOCOL: https
      OVERWRITEHOST: nextcloudsama.devpapangue.com
      TRUSTED_PROXIES: ${TRUSTED_PROXIES}
      NEXTCLOUD_CONFIG_MAINTENANCE_START_HOUR: 2
      DEFAULT_PHONE_REGION: FR

  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  nextcloud_data:
  nextcloud_db:
  caddy_data:
  caddy_config:

# Nextcloud VPS
# samakunchan
# TBPlXei4OLAeFUgklsY6BirqoaLaSWQd4T5o0cHlcS8MoNzZCsQkjVR24ZtCDBIs6FvhLr9C4kam04rLmK4ZRb21bmnFe5KqteGQV0xQDddw6gqGVVgl8ET8Bz14rZvV
# https://nextcloudsama.devpapangue.com
# http://51.77.140.50:8091
# root: nextcloud-sama-974-apple
